module.exports = {
    "BCO. CARIBE\"A\"": "Bancaribe (Clase A)",
    "BCO. CARIBE\\\"A\\\"": "Bancaribe (Clase A)",
    "ARCAINM.VAL.\"B\"": "Arca Inm. Val. (Clase B",
    "ARCAINM.VAL.\\\"B\\\"": "Arca Inm. Val. (Clase B)",
    "BCO.NAC.CREDITO": "Banco Nacional de Crédito",
    "BCO.PROVINCIAL": "Banco Provincial",
    "BOLSAV.CCAS.": "Bolsa de Valores de Caracas",
    "B.DEVENEZUELA": "Banco de Venezuela",
    "C.CAPITAL\"B\"": "C. Capital (Clase B)",
    "C.CAPITAL\\\"B\\\"": "C. Capital (Clase B)",
    "CR.CARABOBO": "Ceramicas Carabobo",
    "CORP.GPO.QUIM.": "CORP.GPO.QUIM.",
    "CORIMONC.A.": "CORIMONC (Clase A)",
    "DOMINGUEZ&CIA": "Dominguez & Cia",
    "PRODUCTOSEFE": "Productos EFE",
    "ENVASESVZLOS.": "Envases Venezolanos",
    "FIVENCAF.C.\"B\"": "Fivenca F.C (Clase B)",
    "FIVENCAF.C.\\\"B\\\"": "Fivenca F.C (Clase B)",
    "FAB.N.CEMENTOS": "Fabrica Nacional de Cementos",
    "G.MANTRACLASEB": "G. Mantra (Clase B)",
    "GRUPOZULIANO": "Grupo Zuliano",
    "I.CRECEPYMES-B-": "I. Crece Pymes (Clase B)",
    "INVACAI. C.\"A\"": "Invaca I.C (Clase A)",
    "INVACAI. C.\\\"A\\\"": "Invaca I.C (Clase A)",
    "INVACAI. C.\"B\"": "Invaca I.C (Clase B)",
    "INVACAI. C.\\\"B\\\"": "Invaca I.C (Clase B)",
    "MANPA,C.A.SACA": "Manpa, C.A.SACA",
    "MONTESCO\"B\"": "Montesco (Clase B)",
    "MONTESCO\\\"B\\\"": "Montesco (Clase B)",
    "MERCANTIL S.(A)": "Mercantil S. (Clase A)",
    "MERCANTIL S.(B)": "Mercantil S. (Clase B)",
    "F.PETROLIA\"B\"": "F. Petrolia (Clase B)",
    "F.PETROLIA\\\"B\\\"": "F. Petrolia (Clase B)",
    "PROAGRO": "Proagro",
    "PIVCACLASE\"B\"": "Pivca (Clase B)",
    "PIVCACLASE\\\"B\\\"": "Pivca (Clase B)",
    "PROTINAL": "Protinal",
    "RONSTA.TERESA": "Ron Santa Teresa",
    "R.S.TERESA\"B\"": "Ron Santa Teresa (Clase B)",
    "R.S.TERESA\\\"B\\\"": "Ron Santa Teresa (Clase B)",
    "SIVENSA,S.A.": "Sivensa,S.A.",
    "CANTVCLASE(D)": "Cantv (Clase D)",
    "T.PALOGRANDE": "T. Palogrande",
    "VENEALTERNA\"B\"": "Venealterna (Clase B)",
    "VENEALTERNA\\\"B\\\"": "Venealterna (Clase B)"
};