module.exports = {
    "BCO. CARIBE \"A\"": "Bancaribe (Clase A)",
    "ARCA INM.VAL. \"B\"": "Arca Inm. Val. (Clase B",
    "BCO.NAC.CREDITO": "Banco Nacional de Crédito",
    "BCO. PROVINCIAL": "Banco Provincial",
    "BOLSA V. CCAS.": "Bolsa de Valores de Caracas",
    "B.DE VENEZUELA": "Banco de Venezuela",
    "C.CAPITAL \"B\"": "C. Capital (Clase B)",
    "CR.CARABOBO": "Ceramicas Carabobo",
    "CORP.GPO.QUIM.": "Corporación Grupo Quimico",
    "CORIMON C.A.": "Corimon (Clase A)",
    "DOMINGUEZ & CIA": "Dominguez & Cia",
    "PRODUCTOS EFE": "Productos EFE",
    "ENVASES VZLOS.": "Envases Venezolanos",
    "FIVENCA F.C. \"B\"": "Fivenca F.C (Clase B)",
    "FAB.N.CEMENTOS": "Fabrica Nacional de Cementos",
    "G.MANTRA CLASE B": "G. Mantra (Clase B)",
    "GRUPO ZULIANO": "Grupo Zuliano",
    "I.CRECEPYMES -B-": "I. Crece Pymes (Clase B)",
    "INVACA I. C. \"A\"": "Invaca I.C (Clase A)",
    "INVACA I. C. \"B\"": "Invaca I.C (Clase B)",
    "MANPA, C.A. SACA": "Manpa, C.A.SACA",
    "MONTESCO \"B\"": "Montesco (Clase B)",
    "MERCANTIL S.(A)": "Mercantil S. (Clase A)",
    "MERCANTIL S.(B)": "Mercantil S. (Clase B)",
    "F.PETROLIA \"B\"": "F. Petrolia (Clase B)",
    "PROAGRO": "Proagro",
    "PIVCA CLASE \"B\"": "Pivca (Clase B)",
    "PROTINAL": "Protinal",
    "RON STA. TERESA": "Ron Santa Teresa",
    "R.S.TERESA \"B\"": "Ron Santa Teresa (Clase B)",
    "SIVENSA, S.A.": "Sivensa,S.A.",
    "CANTV CLASE (D)": "Cantv (Clase D)",
    "T. PALO GRANDE": "T. Palogrande",
    "VENEALTERNA \"B\"": "Venealterna (Clase B)"
};